### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexandru-dinu** [alexandru-dinu/alexandru-dinu.github.io#1]
- [x] add tags (+ list all posts with given tag)
- [x] add LaTeX support
- [x] add links to socials
- [x] add profile picture
- [ ] all tags list
